/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imooc_ffmpegpcmencode_MainActivity */

#ifndef _Included_com_imooc_ffmpegpcmencode_MainActivity
#define _Included_com_imooc_ffmpegpcmencode_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imooc_ffmpegpcmencode_MainActivity
 * Method:    helloFFmpeg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_imooc_ffmpegpcmencode_MainActivity_helloFFmpeg
  (JNIEnv *, jobject);

/*
 * Class:     com_imooc_ffmpegpcmencode_MainActivity
 * Method:    pcmToaac
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_imooc_ffmpegpcmencode_MainActivity_pcmToaac
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
